# Generated by Django 4.2 on 2025-08-19 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_canvas_domain(apps, schema_editor):
    CanvasOAuth2Token = apps.get_model('canvas_oauth', 'CanvasOAuth2Token')
    domain = getattr(settings, 'CANVAS_OAUTH_CANVAS_DOMAIN', 'canvas.instructure.com')
    CanvasOAuth2Token.objects.filter(canvas_domain__isnull=True).update(canvas_domain=domain)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvas_oauth', '0002_alter_canvasoauth2token_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasoauth2token',
            name='canvas_domain',
            field=models.CharField(blank=True, help_text="Canvas domain (e.g., 'canvas.school.edu')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='canvasoauth2token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='canvasoauth2token',
            unique_together={('user', 'canvas_domain')},
        ),
        migrations.RunPython(
            code=set_canvas_domain,
        ),
        migrations.AlterField(
            model_name='canvasoauth2token',
            name='canvas_domain',
            field=models.CharField(help_text="Canvas domain (e.g., 'canvas.school.edu')", max_length=255, null=False, blank=False),
        ),
    ]
